server:
  port: 3357
spring:
  application:
    name: employee-information-systems
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_master
    username: postgres
    password: Fariyudantas1
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
debug: true